### ISSUE TITLE
Learning Rate

### ISSUE THREAD

**Issue by JoshVarty** [JoshVarty/pytorch-retinanet#5]
I'd like to match our learning rate to Detectrons.

In the config they define: 

```yaml
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.00125
  GAMMA: 0.1
  MAX_ITER: 720000
  STEPS: [0, 480000, 640000]
```

```
main()
    train_model()
      get_lr_at_iter(it)
            lr_func_steps_with_decay(cur_iter)
                  get_step_index(cur_iter)
      UpdateWorkspaceLr(it)
```
